#!/bin/sh
# -*- sh -*-

#
# bootstrap
#
# (C) 2009 Nextworks SRL
#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

me=bootstrap

echo "${me}: Bootstrapping directory $PWD"
autoreconf -i -f -Wall -Werror $@ || exit 1

exit 0
